CREATE TABLE CUSTOMER(ID INTEGER NOT NULL, NAME VARCHAR(255),ADDRESS VARCHAR(255),DATE_OF_BIRTH DATE, ID_DOCUMENT_NUMBER VARCHAR(255), IBAN VARCHAR(255), USER_NAME VARCHAR(255), PASSWORD VARCHAR(255), CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID));

