-- todo
--  http://localhost:8080/h2-console
CREATE TABLE IF NOT EXISTS CUSTOMER(ID INT PRIMARY KEY, NAME VARCHAR(255),ADDRESS VARCHAR(255),DATE_OF_BIRTH DATE, ID_DOCUMENT_NUMBER VARCHAR(255), IBAN VARCHAR(255), USERNAME VARCHAR(255), PASSWORD VARCHAR(255), REMOVE_COLUMN VARCHAR(255));